# Generated by Django 6.0 on 2026-01-02 09:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('branch', models.CharField(max_length=200, verbose_name='Филиал')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта (рабочая)')),
                ('personal_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона может содержать только цифры и символы: +, (, ), -, пробел.', regex='^[0-9+\\(\\)\\-\\s]+$')], verbose_name='Номер телефона (личный)')),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона может содержать только цифры и символы: +, (, ), -, пробел.', regex='^[0-9+\\(\\)\\-\\s]+$')], verbose_name='Номер телефона (рабочий)')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Изменяемый атрибут')),
                ('new_value', models.TextField(verbose_name='Новое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Предложение по исправлению',
                'verbose_name_plural': 'Предложения по исправлению',
            },
        ),
    ]
