# Generated by Django 5.2.9 on 2026-01-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionproposal',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Сотрудник', max_length=150, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='correctionproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='correctionproposal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='correctionproposal',
            name='field_name',
            field=models.CharField(max_length=100, verbose_name='Имя поля'),
        ),
    ]
